# Adds the necessary Hugo metadata when an existing mod update is ported to a new Minecraft version.
name: Add Mod Port
run-name: Add ${{ inputs.mod }} ${{ inputs.mod_version }} build for ${{ inputs.mc_version }} (${{ inputs.modloader }})

on:
  workflow_dispatch:
    inputs:
      mod:
        description: "Mod ID (as it appears in config.toml)"
        required: true
      modloader:
        description: "Mod loader (fabric or neoforge)"
        required: true
      mod_version:
        description: "Mod version (without v or -MC)"
        required: true
      mc_version:
        description: "Minecraft version"
        required: true
      fapi_version:
        description: "Fabric API version (if modloader is fabric)"
        required: false
      file_id:
        description: "CurseForge file ID"
        required: true
      distinct_id:
        required: false

jobs:
  update-post:
    runs-on: ubuntu-latest
    steps:

    - name: Echo distinct ID ${{ inputs.distinct_id }}
      run: echo ${{ inputs.distinct_id }}

    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        # So that the hugo workflow runs automatically.
        token: ${{ secrets.WIMODS_NET_PUBLISH_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
        cache: "pip"
        cache-dependency-path: scripts/requirements.txt

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Run add_mod_port.py
      run: |
        python scripts/add_mod_port.py \
          "${{ inputs.mod }}" \
          "${{ inputs.modloader }}" \
          "${{ inputs.mod_version }}" \
          "${{ inputs.mc_version }}" \
          ${{ inputs.modloader == 'fabric' && format('--fapi_version {0}', inputs.fapi_version) || '' }} \
          "${{ inputs.file_id }}"

    - name: Commit changes
      run: |
        MOD="${{ inputs.mod }}"
        MOD_VERSION="${{ inputs.mod_version }}"
        MC_VERSION="${{ inputs.mc_version }}"
        MODLOADER="${{ inputs.modloader }}"
        git config --local user.email "contact.wurstimperium@gmail.com"
        git config --local user.name "Wurst-Bot"
        git add .
        git commit -m "[Wurst-Bot] Port $MOD $MOD_VERSION to Minecraft $MC_VERSION ($MODLOADER)"
        git push
