name: Announce Mod Update
run-name: Announce ${{ github.event.inputs.mod }} ${{ github.event.inputs.mod_version }} update on WurstForum

on:
  workflow_dispatch:
    inputs:
      mod:
        description: "Mod ID (as it appears in config.toml)"
        required: true
      mod_version:
        description: "Mod version (without v or -MC)"
        required: true
      dry_run:
        description: "Don't actually upload the announcement"
        type: boolean
        default: false

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
        cache-dependency-path: scripts/requirements.txt

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Run announce_mod_update.py
      env:
        WURSTFORUM_TOKEN: ${{ secrets.WF_BOT_TOKEN }}
      run: |
        python scripts/announce_mod_update.py \
          "${{ github.event.inputs.mod }}" \
          "${{ github.event.inputs.mod_version }}" \
          ${{ github.event.inputs.dry_run && '--dry-run' || '' }}
