name: Announce that the previous Fabric API still works

on:
  workflow_dispatch:
    inputs:
      fapi_version:
        description: "Fabric API version (e.g. '0.115.0+1.21.5')"
        required: true
      mc_version:
        description: "Minecraft version (e.g. '25w03a')"
        required: true
      dry_run:
        description: "Don't actually upload the announcement"
        type: boolean
        default: false
      distinct_id:
        required: false

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:

    - name: Echo distinct ID ${{ inputs.distinct_id }}
      run: echo ${{ inputs.distinct_id }}

    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
        cache: "pip"
        cache-dependency-path: scripts/requirements.txt

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Run announce_prev_fabric_api_still_works.py
      env:
        WURSTFORUM_TOKEN: ${{ secrets.WF_BOT_TOKEN }}
      run: |
        python scripts/announce_prev_fabric_api_still_works.py \
          "${{ inputs.fapi_version }}" \
          "${{ inputs.mc_version }}" \
          ${{ inputs.dry_run && '--dry-run' || '' }}
